### PR TITLE
Config

### PR DESCRIPTION
**Pull request by alexbeletsky**
My preference is not to `.install()` module, but use as `log` object in my modules. To be able to change configuration as,

``` js
var log = require('better-log').config({depth: 4});
```

### CODE REVIEW

**Comment by RReverser** [comment]
There is already [`betterLog.setConfig`](https://github.com/RReverser/better-log/blob/master/index.js#L33) for this, just forgot to document it, sorry. Does this add anything different?

**Comment by RReverser** [comment]
Also, I'd really encourage using `.install` - you're not losing anything as API is completely compatible, but still getting colorful output even for logs from third-party libraries which don't use `better-log` directly.

**Comment by alexbeletsky** [comment]
Existing `setConfig` doesn't support chain call, e.g.

```
var log = require('better-log').setConfig({depth: 4});
log.log();
```

would crash, as access to `undefined`.

I also changed it from `setConfig` to just `config`, since it looks a bit nicer to me.. but doesn't do any difference. :)

**Comment by RReverser** [comment]
Ah, I'll add chaning if you wish. Although I wouldn't change (break) API now without any specific purpose :)

**Comment by RReverser** [comment]
Released chaining support for `setConfig` in 1.3.1.

**Pull request closed without merging**
